apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  steps:
    - name: run-flake8
      image: python:3.9
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -e
        pip install flake8
        echo "Running flake8 lint check..."
        # Ignore line length (E501)
        flake8 . --ignore=E501
